version: '3'
services:
  go-funny-endpoints:
    image: go-funny-endpoints
    ports:
      - "18080:18080"
    expose:
      - "18080"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 18080
      GODEBUG: "http2debug=1"
